application: testgaedjango
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: main.application
  
libraries:

- name: django
  version: "1.4"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'Testdj.settings'
